[package]
name = "ta-ko-ho/ta-ko-ho-sveltekit-3-a81"
version = "0.1.1"
description = "wasmer-tests/wasmer-edge-svelte-sample website"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "build"
